### ISSUE TITLE
Design the applications background

### ISSUE THREAD

**Issue by OladapoAjala** [OladapoAjala/weather-app#4]
Using vanilla JS, CSS, & HTML implement a responsive background for the weather application.

Hint: At the center of the background is where the main application would sit.

**Comment by OladapoAjala** [comment]
Who is working on this @VictoriaAjala @Tobbie2 ?

**Comment by OladapoAjala** [comment]
@Tobbiloba are you done with this?

**Comment by Tobbiloba** [comment]
yes i'm
